[package]
name = "rust_ffi"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust_ffi"
path = "rust_ffi/fraction_tester.rs"

[lib]
name = "fraction"
path = "libfraction.rs"
crate-type = ["cdylib"]
