/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FractionTester */

#ifndef _Included_FractionTester
#define _Included_FractionTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FractionTester
 * Method:    fractionMultiply
 * Signature: (LFraction;LFraction;)I
 */
JNIEXPORT jint JNICALL Java_FractionTester_fractionMultiply
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
