/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_ffi_FractionTester */

#ifndef _Included_java_ffi_FractionTester
#define _Included_java_ffi_FractionTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_ffi_FractionTester
 * Method:    fractionMultiply
 * Signature: (Ljava_ffi/Fraction;Ljava_ffi/Fraction;)I
 */
JNIEXPORT jint JNICALL Java_java_1ffi_FractionTester_fractionMultiply
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
